export { default as Navbar } from './Navbar';
export { default as HeroSection } from './HeroSection';
export { default as Features } from './Features';
export { default as Brands } from './Brands';
export { default as Services } from './Services';
export { default as About } from './About';
export { default as Statistics } from './Statistics';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
